name: SDK feature request
description: Suggest an idea for the SDK
body:
  - type: checkboxes
    attributes:
      description: Please verify that you've followed these steps
      options:
        - label: I understand that if I ignore these instructions, my **issue may be closed without review**.
          required: true
        - label: I have made sure that there are **no similar opened issues**.
          required: true
        - label: I have made sure that the **SDK version matches the latest release**.
          required: false
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      value: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      value: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      value: If applicable, add a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      value: If applicable, add any other context or screenshots about the feature request here.
    validations:
      required: false
